// src/utils/mockData.ts
import { Listing, RoommatePost, CommunityPost } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    owner_id: 'owner1',
    title: 'Premium Self-Contain near FULAFIA Main Gate',
    description: 'Beautifully finished self-contain with modern tiles, pop ceiling, and steady water supply. Just a 5-minute walk to the university main gate.',
    property_type: 'self_contain',
    university_tags: ['fulafia'],
    rent: 45000,
    payment_frequency: 'yearly',
    lease_type: 'standard',
    caution_fee: 5000,
    address: 'Mararaba Akunza, near FULAFIA Main Gate',
    lat: 8.5075,
    lng: 8.5235,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1000&auto=format&fit=crop',
    ],
    video_url: null,
    virtual_tour_url: null,
    amenities: ['Water', 'Electricity', 'Security', 'Kitchen'],
    house_rules: 'Female students only. No loud music.',
    no_increment_pledge: true,
    rent_history: [
      { year: 2024, amount: 45000 },
      { year: 2023, amount: 40000 },
    ],
    move_in_ready: true,
    move_in_checklist: { roof: true, water: true, electricity: true, toilet: true, paint: true, gate: true, generator: true, borehole: true },
    last_confirmed_at: new Date().toISOString(),
    is_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    beds: 1,
    baths: 1,
  },
  {
    id: '2',
    owner_id: 'owner2',
    title: 'Spacious Room & Parlour in NSUK Keffi',
    description: 'Very large room and parlour with ensuite bathroom. Gated environment.',
    property_type: 'room',
    university_tags: ['nsuk_keffi'],
    rent: 85000,
    payment_frequency: 'yearly',
    lease_type: 'standard',
    caution_fee: 10000,
    address: 'High Court Area, Keffi',
    lat: 8.8480,
    lng: 7.8740,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop',
    ],
    video_url: null,
    virtual_tour_url: null,
    amenities: ['Water', 'Electricity', 'Parking'],
    house_rules: null,
    no_increment_pledge: false,
    rent_history: [],
    move_in_ready: false,
    move_in_checklist: { roof: true, water: true },
    last_confirmed_at: null,
    is_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    beds: 1,
    baths: 1,
  },
];

export const MOCK_ROOMMATES: RoommatePost[] = [
  {
    id: 'r1',
    user_id: 'u1',
    user_name: 'Blessing',
    university: 'fulafia',
    academic_level: '300L',
    monthly_budget: 15000,
    area_preference: 'Mararaba',
    property_type: 'Self-contain',
    lifestyle_tags: ['Female', 'Quiet', 'Non-smoker'],
    bio: 'Looking for a clean and quiet roommate to share a self-contain.',
    is_active: true,
    expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const MOCK_COMMUNITY: CommunityPost[] = [
  {
    id: 'c1',
    author_id: 'u2',
    author_name: 'John',
    university: 'fulafia',
    tag: 'scam_alert',
    content: 'Beware of a landlord claiming to have a flat in Gandu for 20k. He asks for "commitment fee" before viewing.',
    scam_landlord_name: 'Mr. X',
    scam_area: 'Gandu Site',
    is_pinned: true,
    is_removed: false,
    created_at: new Date().toISOString(),
  },
];
